version: '3.8'  # Specifies the version of the Docker Compose file format.

services:  # Defines the services that will be run.

  dind:  # The Docker-in-Docker (DinD) service.
    image: docker:20.10-dind  # Uses Docker-in-Docker image.
    privileged: true  # Enables privileged mode for DinD to run Docker commands inside the container.
    networks:
      jenkins:
        aliases: 
         - docker  # Alias for easy communication with Jenkins.
    environment:
      DOCKER_TLS_CERTDIR: "/certs"  # Enables TLS and specifies the directory for certificates.
    ports:
      - "2376:2376"  # Exposes Docker API over TLS.

  jenkins:  # The Jenkins service for CI/CD.
    image: jenkins/jenkins:lts-jdk11  # Uses Jenkins LTS image with JDK 11.
    environment:
      DOCKER_HOST: "tcp://docker:2376"  # Connects Jenkins to the Docker service (DinD).
      DOCKER_TLS_VERIFY: 1  # Verifies Docker communication using TLS.
    volumes:
      - /usr/bin/docker:/usr/bin/docker  # Allows Jenkins to run Docker commands.
    ports:
      - "8080:8080"  # Exposes Jenkins UI on port 8080.
      - "50000:50000"  # Exposes Jenkins agent communication port.

networks:
  jenkins:
    driver: bridge  # Creates a bridge network for isolated communication between services.

volumes:  # Declares persistent volumes for data storage.
  jenkins-data:
  docker-certs-ca:
  docker-certs-client:
